(require "monogram.scm")

(define (link name url)
  (<a> ((href url))
    (: name)))

(define (banner)
  (: "<!-- TODO: Banner -->"))

(define (header)
  (<header> ((class "main-header"))
    (<h1> ()
      (<a> ((href "/"))
        (: "pelliott")
        (<span> ((class "tinyca")) (: ".ca"))))
    (<nav> ()
      (link "blog" "/blog")
      (link "bookmarks" "/bookmarks")
      (link "about" "/about"))))

(define (footer)
  (<footer> ((class "main-footer"))
    (<nav> ()
      (link "sitemap" "/sitemap")
      (link "contact" "/contact")
      (link "site source repo" "https://petelliott.github.com")
      (link "my github" "https://petelliott.github.com"))
    (<p> ()
      (: "©/❤ ")
      (monogram))))



(define (css path)
  (<link> ((rel "stylesheet")
           (href path))))

(define-component (page (title) . body)
  (!DOCTYPE 'html)
  (<html> ()
    (<head> ()
      (<meta> ((charset "utf-8")))
      (<meta> ((name "viewport") (content "width=device-width, initial-scale=1")))
      (css "/css/elements.css")
      (monogram-css)
      (css "/css/main.css")
      (<title> ()
        (: title)))
    (<body> ()
      (declare-monogram)
      (banner)
      (header)
      (<main> ()
        (body))
      (footer))))
