(define-module (renderers)
  #:use-module (schingle template mustache)
  #:use-module (schingle render)
  #:use-module (schingle util)
  #:use-module (ice-9 textual-ports)
  #:use-module (markdown)
  #:use-module (parameters))

(add-renderer ".md" markdown->html)
(add-renderer ".mustache" (mustache-renderer *global-template-params*))

(define md-template (mustache-compile "mdpage.mustache"))
(add-renderer ".page.md" (lambda (content)
                           (define str (string/bytevector->string content))
                           (define-values (frontmatter body)
                             (call-with-input-string str
                               (lambda (port)
                                 (define frontmatter (read port))
                                 (if (list? frontmatter)
                                     (values frontmatter (get-string-all port))
                                     (values '() str)))))
                           (md-template (append frontmatter `((body . ,(markdown->html body)))))))
